$(document.body).on("click.fecss.can-close.close-btn",".can-close .close-btn",{},function(c){c.preventDefault(),console.log("body trigger:click.fecss.can-close.close-btn"),$(this).closest(".can-close").removeClass("active")});
$(document.body).on("fecss.default",null,{},function(o){console.log("body trigger:fecss.default")}),$(document.body).on("fecss.init",null,{},function(o){console.log("body trigger:fecss.init")}),$(document.body).on("fecss.window.unload",null,{},function(o,n){console.log("body trigger:fecss.window.unload: "+JSON.stringify(n))}),$(document.body).on("fecss.ajax.success",null,{},function(o){console.log("body trigger:fecss.ajax.success")}),$(document.body).on("fecss.keydown",null,{},function(o,n){console.log("body trigger:fecss.keydown: "+JSON.stringify(n))}),$(document.body).on("DOMSubtreeModified",null,{},function(o,n){console.log("body trigger:DOMSubtreeModified: "+JSON.stringify(n))});
$(document.body).on("fecss.changeDOM",".fecss-change-dom",{},function(e,c){console.log(".fecss-change-dom trigger:fecss.changeDOM")}),$(document.body).on("DOMSubtreeModified",".fecss-change-dom",{},function(e,c){$(this).trigger("fecss.changeDOM")});
$(document.body).on("fecss.modal.show.after",null,{},function(e,o,t){e.preventDefault(),console.log("body trigger:fecss.modal.show.after")}),$(document.body).on("fecss.modal.hide.after",null,{},function(e,o,t){e.preventDefault(),console.log("body trigger:fecss.modal.hide.after")}),$(document.body).on("fecss.active.set",".fecss-modal .white-container",{},function(e,o,t){e.preventDefault(),console.log(".white-container trigger:fecss.active.set")}),$(document.body).on("fecss.active.unset",".fecss-modal .white-container",{},function(e,o,t){e.preventDefault(),console.log(".white-container trigger:fecss.active.unset")});

$(document.body).on("click.fecss.scrollto",".scrollto",{},function(t){t.preventDefault(),console.log("body trigger:click.fecss.scrollto");var o=$(this),l=$(o.attr("href")).eq(0),e=parseInt(o.attr("data-scrollto-diff"))||0,r=parseInt(o.attr("data-scrollto-speed"))||777;$("html, body").animate({scrollTop:l.offset().top+e},r)});
$(document.body).on("fecss.url-history.get",null,{},function(t,e,n,i){t.preventDefault(),$.get(e,{},function(t){var o=[];o=""!=n&&"undefined"!=typeof n&&"undefined"!=n?n.split(","):["div:div"];for(var r in o){var d=o[r].trim().split(":");$(d[0]).html($(t).find(d[1]).eq(0).html())}1==i&&window.history.pushState({href:e,target:n},null,e)})}),window.addEventListener("popstate",function(t){$(document.body).trigger("fecss.url-history.get",[window.location.pathname,t.state.target,!1])},!1);
$(document.body).on("click.fecss",".content-container",{},function(e,n){$(".menu-container .menu-list .item.dialoged.active").removeClass("active")});
$(document.body).on("fecss.menu-list.item.contented.click",null,{},function(e,t){var i=t,s=i.attr("href"),c=i.attr("data-target");if(i.hasClass("url-history"))if(""!=c&&"undefined"!=typeof c&&"undefined"!=c){var l=c.split(",");s=l[0],s=s.split(":"),s=s[0]}else s=$(".item-block.active").attr("id");var n=$(s+".item-block");if(n.size())n.hasClass("active")||($(".item-block").removeClass("active"),n.addClass("active"));else{var a=$("<div/>",{id:s,"class":"item-block "});$(".item-block").removeClass("active"),a.addClass("active")}$("html, body").animate({scrollTop:0},333),i.closest(".menu-list").find(".item.active").removeClass("active"),i.closest(".item").addClass("active")}),$(document.body).on("fecss.menu-list.item.dialoged.click",null,{},function(e,t){var i=t;i.closest(".menu-list").find(".item.active").removeClass("active"),i.closest(".item").addClass("active").find(".input-block input").eq(0).trigger("focus")}),$(document.body).on("click.fecss.menu-list.item.contented.a",".menu-list .item.contented a",{},function(e){e.preventDefault(),$(document.body).trigger("fecss.menu-list.item.contented.click",[$(this)]),$(document.body).trigger("fecss.menu-container.hide")}),$(document.body).on("click.fecss.menu-list.item.dialoged.a",".menu-list .item.dialoged a",{},function(e){e.preventDefault(),$(document.body).trigger("fecss.menu-list.item.dialoged.click",[$(this)])});
$(document.body).on("fecss.menu-container.show",null,{},function(n){$(".window-width-xs .menu-container, .window-width-sm .menu-container").addClass("active")}),$(document.body).on("fecss.menu-container.hide",null,{},function(n){$(".window-width-xs .menu-container, .window-width-sm .menu-container").removeClass("active")}),$(document.body).on("click.fecss.menu-container-show",".menu-container-show",{},function(n){n.preventDefault(),$(document.body).trigger("fecss.menu-container.show")}),$(document.body).on("click.fecss.menu-container-hide",".menu-container-hide",{},function(n){n.preventDefault(),$(document.body).trigger("fecss.menu-container.hide")});